ALTER TABLE "decoration_images" ALTER COLUMN "url" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "address" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "verified" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "verification_submitted" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "rating" SET DEFAULT '0';--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "num_ratings" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "latitude" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "longitude" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "country" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "city" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decorations" ALTER COLUMN "year" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "notifications" ALTER COLUMN "title" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "notifications" ALTER COLUMN "body" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "notifications" ALTER COLUMN "unread" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ratings" ALTER COLUMN "rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "reports" ALTER COLUMN "unresolved" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "routes" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "premium" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "is_admin" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "notifications_on_app_verification" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "notifications_on_app_rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "notifications_by_email_verification" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "notifications_by_email_rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "verifications" ALTER COLUMN "document" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "verifications" ALTER COLUMN "new" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "verifications" ALTER COLUMN "approved" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "verifications" ALTER COLUMN "rejected" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "verifications" ALTER COLUMN "archived" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "views" ALTER COLUMN "created_at" DROP NOT NULL;